export const eventTypes = [
  // ── Pedido / pagamento
  "PEDIDO_CRIADO",
  "PEDIDO_SINCRONIZADO",
  "PEDIDO_PAGAMENTO_APROVADO",
  "PEDIDO_PAGAMENTO_RECUSADO",
  "PEDIDO_CANCELADO_PAGAMENTO",
  // ── Separação / conferência / faturamento
  "SEPARACAO_INICIADA",
  "CONFERENCIA_FINALIZADA",
  "FATURADO",
  // ── Entrega
  "SAIU_PARA_ENTREGA",
  "PEDIDO_EM_ROTA",
  "ENTREGA_REALIZADA",
  "TENTATIVA_ENTREGA_FRUSTRADA",
  "ENTREGA_REAGENDADA",
  // ── Avaliação de atendimento / entrega
  "ATENDIMENTO_AVALIACAO_ENVIADA",
  "ATENDIMENTO_AVALIADO",
  "ENTREGA_AVALIADA",
  // ── Montagem — cliente
  "MONTAGEM_NECESSARIA",
  "LINK_AGENDAMENTO_ENVIADO",
  "MONTAGEM_AGUARDANDO_AGENDAMENTO",
  "MONTAGEM_AGENDADA",
  "LEMBRETE_MONTAGEM_24H",
  "LEMBRETE_MONTAGEM_DIA",
  "MONTADOR_CHEGOU",
  "MONTAGEM_INICIADA",
  "MONTAGEM_FINALIZADA",
  "FOTOS_MONTAGEM_ANEXADAS",
  "LINK_AVALIACAO_MONTAGEM_ENVIADO",
  "AVALIACAO_CLIENTE_RECEBIDA",
  "MONTAGEM_APROVADA_CLIENTE",
  "MONTAGEM_REPROVADA_CLIENTE",
  "MONTAGEM_REAGENDADA_SAC",
  // ── SAC — cliente
  "RECLAMACAO_CLIENTE_ABERTA",
  "SAC_CASO_ABERTO",
  "SAC_RESPONSAVEL_ATRIBUIDO",
  "SAC_EM_ANALISE",
  "SAC_SOLICITOU_INFO",
  "SAC_APROVOU_LIBERACAO",
  "SAC_REPROVOU_LIBERACAO",
  "SAC_ENCERROU_CASO",
  // ── Encerramento
  "JORNADA_ENCERRADA",
  // ── Montador / fornecedor
  "MONTADOR_NOTIFICADO",
  "MONTADOR_LEMBRETE_DIA",
  "MONTADOR_SERVICO_REAGENDADO",
  "MONTADOR_SERVICO_CANCELADO",
  "MONTADOR_CLIENTE_ALTEROU",
  "MONTADOR_FOTOS_PENDENTES",
  "MONTADOR_MONTAGEM_FINALIZADA",
  "MONTADOR_MONTAGEM_REPROVADA",
  "MONTADOR_SAC_ANALISE",
  // ── Pagamentos — fornecedor
  "PAGAMENTO_AGUARDANDO_APROVACAO",
  "PAGAMENTO_BLOQUEADO",
  "PAGAMENTO_LIBERADO",
  "PAGAMENTO_ENVIADO_FINANCEIRO",
  "PAGAMENTO_PROGRAMADO",
  "PAGAMENTO_REALIZADO",
  // ── Erros / sistema
  "INTEGRACAO_WINTHOR_ERRO",
  "MENSAGEM_ERRO_ENVIO",
  // ── Observabilidade — elegibilidade e comissões
  "ORDER_ELIGIBILITY_CHECKED",
  "ASSEMBLY_ITEM_CREATED",
  "COMMISSION_CALCULATED",
  "PAYMENT_RECALCULATED",
  // ── Retrabalho
  "REWORK_CREATED",
  "REWORK_CLASSIFIED",
  "REWORK_RESOLVED",
  // ── PIX
  "PIX_PAYMENT_REQUESTED",
  "PIX_PAYMENT_CONFIRMED",
  "PIX_PAYMENT_FAILED",
  // ── Offline sync
  "OFFLINE_SYNC_COMPLETED",
] as const;

export type EventType = (typeof eventTypes)[number];

export const roles = [
  "ADMIN",
  "GESTOR",
  "OPERACAO",
  "LOGISTICA",
  "SAC",
  "FINANCEIRO",
  "MONTADOR",
  "CONSULTA"
] as const;

export type Role = (typeof roles)[number];

export const providerStatuses = [
  "PRE_CADASTRO",
  "AGUARDANDO_DOCUMENTACAO",
  "AGUARDANDO_ANALISE",
  "EM_ANALISE",
  "APROVADO",
  "REPROVADO",
  "SUSPENSO",
  "INATIVO",
  "BLOQUEADO"
] as const;

export const paymentStatuses = [
  "AGUARDANDO_FINALIZACAO",
  "AGUARDANDO_AVALIACAO_CLIENTE",
  "BLOQUEADO",
  "AGUARDANDO_APROVACAO_SAC",
  "LIBERADO",
  "ENVIADO_FINANCEIRO",
  "PROGRAMADO",
  "PAGO",
  "CANCELADO"
] as const;

export type PaymentStatus = (typeof paymentStatuses)[number];
